patients: configs/patients.tsv
outdir: results
monovar_script: /tzu-share-2/users/students/cornelusp/monovar/monovar/src/monovar.py
monovar_threads: 2
monovar_region: ""
run_monovar: false
run_delsieve_prep: false
run_delsieve: false
min_total_depth: 20
min_alt_reads: 4
min_vaf: 0.0
delsieve_min_ctc_support: 2
delsieve_applauncher: applauncher
delsieve_beast: beast
delsieve_template_stage1: ""
vep_cache: ~/.vep
genome: GRCh38
