patients: configs/patients.patient_03_wxs_ctc_only_compare.tsv
outdir: results
run_monovar: false
run_external_callers: false
run_comparison: false
run_delsieve_prep: false
run_delsieve: true
run_delsieve_from_existing: true
run_delsieve_tree_annotator: true
delsieve_existing_long_table: results/patient_03_wxs_ctc_only/caller_comparison/cache/merged/all_mutations_long.annotated.tsv.gz
min_total_depth: 20
min_alt_reads: 4
min_vaf: 0.0
delsieve_min_ctc_support: 2
delsieve_callers: all
delsieve_min_base_quality: 0
delsieve_min_mapping_quality: 0
delsieve_applauncher: applauncher
delsieve_beast: beast
delsieve_treeannotator: applauncher
delsieve_version_file: /tzu-share-2/users/students/cornelusp/DelSIEVE/version.xml
delsieve_template_stage1: /tzu-share-2/users/students/cornelusp/DelSIEVE/examples/templates/smc_mu_sa_stage_1.xml
delsieve_threads: 8
delsieve_datatype: 1
delsieve_missing_threshold: 1
delsieve_sample_cells: 0
delsieve_sample_loci: 0
delsieve_ignore_sex: false
delsieve_beast_extra_args: ""
delsieve_datacollector_extra_args: ""
delsieve_tree_burnin: 10
delsieve_tree_heights: median
